// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SX6Yg8lY-f3KOAG5V1HJY41atfmhlWA',
    appId: '1:649815946098:web:8cb58799d346106b3ae3eb',
    messagingSenderId: '649815946098',
    projectId: 'car-rental-2b862',
    authDomain: 'car-rental-2b862.firebaseapp.com',
    storageBucket: 'car-rental-2b862.firebasestorage.app',
    measurementId: 'G-E3YL3ES2HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBOgNMOkOZe-rd7n1oLNDjEx11WX_wow',
    appId: '1:696007732318:android:5799979824585d584a58cf',
    messagingSenderId: '696007732318',
    projectId: 'auth01-99776',
    storageBucket: 'auth01-99776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqXkJb-fMCJtyGb329PS3MaobHL7bpqg',
    appId: '1:649815946098:ios:4ed331ed32331c523ae3eb',
    messagingSenderId: '649815946098',
    projectId: 'car-rental-2b862',
    storageBucket: 'car-rental-2b862.firebasestorage.app',
    iosBundleId: 'com.example.instaseries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqXkJb-fMCJtyGb329PS3MaobHL7bpqg',
    appId: '1:649815946098:ios:4ed331ed32331c523ae3eb',
    messagingSenderId: '649815946098',
    projectId: 'car-rental-2b862',
    storageBucket: 'car-rental-2b862.firebasestorage.app',
    iosBundleId: 'com.example.instaseries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwwCJDa7ttIQsIbP7Y1PCnoPC7iIbDDPE',
    appId: '1:649815946098:web:760b52bd95e513d83ae3eb',
    messagingSenderId: '649815946098',
    projectId: 'car-rental-2b862',
    authDomain: 'car-rental-2b862.firebaseapp.com',
    storageBucket: 'car-rental-2b862.firebasestorage.app',
    measurementId: 'G-RFBD9XEY6J',
  );

}